# Generated by Django 5.2.7 on 2025-12-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id_aviso', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del aviso')),
                ('descripcion', models.TextField(verbose_name='Descripción o contenido del aviso')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id_colaborador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fotografia', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'myapp_colaborador',
            },
        ),
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id_contactos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id_noticia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='noticias/')),
            ],
        ),
    ]
