# Generated by Django 5.2.7 on 2025-12-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to='colaboradores/'),
        ),
    ]
