# Generated by Django 5.2.8 on 2025-12-05 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_colaborador_fotografia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactos',
            options={'ordering': ['-fecha_envio']},
        ),
    ]
